[build]
  publish = "public"
  command = "yarn build"
  GATSBY_BASEURL = "https://www.learnitmyway-gatsby.com/"

[context.production.environment]
  GATSBY_BASEURL = "https://staging--learnitmyway-gatsby.netlify.com/"